### ISSUE TITLE
Code style fomatter for checking code style and formatting

### ISSUE THREAD

**Issue by PommesPeter** [visualDust/neetbox#24]
As you know, a user-friendly code style will improve the continuity of code development. Methods we need to discuss. There are the design I think,

1. Using `black` formatter for code format.
2. Using `isort` to manage imported modules.
3. Using `flake8` for checking code style.

Welcome to give more methods to optimize it.

**Comment by visualDust** [comment]
Great idea. Please put the instructions into the 'code of conduct'. You can find it [here](https://github.com/visualDust/neetbox/blob/master/CODE_OF_CONDUCT.md). The file was generated by github. You can change the content as you wish.

**Comment by visualDust** [comment]
Please provide how contributors standardize their code step by step. Listing to the steps of the procedure may find it well when someone is gonna change the code.

**Comment by PommesPeter** [comment]
> Great idea. Please put the instructions into the 'code of conduct'. You can find it [here](https://github.com/visualDust/neetbox/blob/master/CODE_OF_CONDUCT.md). The file was generated by github. You can change the content as you wish.
> 

Yep, Later I will update it.

**Comment by PommesPeter** [comment]
> Please provide how contributors standardize their code step by step. Listing to the steps of the procedure may find it well when someone is gonna change the code.

It's an automation action. We should use the `pre-commit`, a Python package, to normalize the code. it can be found [here](https://github.com/pre-commit/pre-commit).

To implement, we need to config `.pre-commit.yaml` to set the function of standardized operations.

**Comment by PommesPeter** [comment]
I should pick this issue up again...
