### ISSUE TITLE
Better X platform NEETBOX daemon

### ISSUE THREAD

**Issue by therainisme** [visualDust/neetbox#32]
I was trying to use NEETBOX daemon on windows, but it says

```bash
[OK]2023-04-14-12:00:25 > NEETBOX/init > Loaded workspace config from D:\GaGs\ntb-test1\neetbox.toml.
2023-04-14-12:00:25 > neetbox.daemon._daemon_client/connect_daemon > Connecting daemon at localhost:20202 ...
2023-04-14-12:00:29 > neetbox.daemon/__attach_daemon > No daemon running at localhost:20202, trying to create daemon...
[ERROR]2023-04-14-12:00:29 > neetbox.daemon/__attach_daemon > Could not fork subprocess because module 'os' has no attribute 'fork'. NEETBOX daemon won't work on Windows.
```
Would NEETBOX daemon support windows in the future?

This is my configuration file:
```toml
name = "vivy"

[logging]

[pipeline]

[integrations]
datasets = []

[daemon]
enable = true
server = "localhost"
port = 20202
updateInterval = 10
uploadInterval = 10
info = [ "log", "status",]

[integrations.environment]
gpus = "auto"
```

**Comment by visualDust** [comment]
NEETBOX will finally support daemon on windows. However, there is a long term struggle before it comes true. NEETBOX temporarily not supporting daemon features on Windows, reasons are listed in how daemon is created.

When a project with neetbox launches, neetbox will check if there is any daemon running on `localhost: 20202` as your configuration said. If not, it forks a subprocess using `os.fork()`([see the code here](https://github.com/visualDust/neetbox/blob/master/neetbox/daemon/__init__.py#L29)) for daemon and then uses package `python-daemon` to create the daemon process([see the code here](https://github.com/visualDust/neetbox/blob/master/neetbox/daemon/__init__.py#L46)).

The bad news is, `os.fork()` and `python-daemon` only work on *nix OS. We need to rewrite the code in [neetbox/daemon/__init__.py](https://github.com/visualDust/neetbox/blob/master/neetbox/daemon/__init__.py#L15) with `multiprocessing` before it supports Windows.

The good news is, the code is clear and it won't affect other codes and it seems easy to modify.

Another bad news is, I've been working with archlinux recently and I do not have any Windows PC. It's a little bit hard for me to debug the code on windows. Hopefully someone else would help.

**Comment by visualDust** [comment]
Another problem is, if we rewrite the code with `multiprocessing`, the daemon dies when the main process dies. So the daemon connector ([see the code here](https://github.com/visualDust/neetbox/blob/master/neetbox/daemon/_daemon_client.py#L107)) must have the ability to identify the death of the daemon process, and launch another one.

**Comment by visualDust** [comment]
A preview has been published [here](https://github.com/visualDust/neetbox/releases/tag/0.1.509). Notice that when you first do `neet init` and run your project on Windows, please make sure you're running in a terminal with administrator privileges. NEETBOX daemon now works as a service on windows.
This feature was introduced by @AndPuQing . Further discussions are welcomed.

**Comment by visualDust** [comment]
PaperCube is amazing.

**Comment by visualDust** [comment]
#44
