### ISSUE TITLE
Moving to 'rich' for better terminal outputs

### ISSUE THREAD

**Issue by RockOsas** [visualDust/neetbox#39]
NEETBOX performs strange in cmd:

![image](https://user-images.githubusercontent.com/91041243/232440970-396b267f-7390-4e31-ac3c-ffde9ef3d1aa.png)

the output log in cmd is broken. But the logs in files are fine. Is there something wrong?

**Comment by visualDust** [comment]
Oops, I think cmd does not support ANSI escape sequence. [Here](https://github.com/adoxa/ansicon) is a work around. However, we are moving to [rich](https://github.com/textualize/rich) for better output, so things are gonnaq be fine at time.

**Comment by PommesPeter** [comment]
ANSI escape sequence is not support in cmd, we need to update the `colored` function.

**Comment by visualDust** [comment]
#43 solves the problem.
